//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jsa.ViewsModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jsa.ViewsModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل وصف النشاط.
        /// </summary>
        internal static string ActivityView_DescriptionMissing {
            get {
                return ResourceManager.GetString("ActivityView_DescriptionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توجد مهام طباعة في الخلفية
        ///فضلاً إنتظر قليلاً حتى يتم الإنتهاء من طباعتها.
        /// </summary>
        internal static string BackgroundPrintJobsExist {
            get {
                return ResourceManager.GetString("BackgroundPrintJobsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنتهت عملية تسجيل العقود في برنامج العقار بنجاح.
        /// </summary>
        internal static string BulkIresContractsView_BulkSaveFinished {
            get {
                return ResourceManager.GetString("BulkIresContractsView_BulkSaveFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنت على وشك حفظ عقود سنة كاملة في برنامج العقار.
        ///تأكد من إغلاق جميع العقود المفتوحة قبل مواصلة العملية.
        ///في حال مواصلة العملية لن تستطيع التراجع، هل تريد مواصلة العملية؟.
        /// </summary>
        internal static string BulkIresContractsView_SaveToIresWarning {
            get {
                return ResourceManager.GetString("BulkIresContractsView_SaveToIresWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدد مسار نموذج المطالبة في الخيارات أولاً.
        /// </summary>
        internal static string ClaimView_ClaimTemplMissing {
            get {
                return ResourceManager.GetString("ClaimView_ClaimTemplMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احفظ البيانات اولاً.
        /// </summary>
        internal static string ClassesView_CannotOpenBeforSave {
            get {
                return ResourceManager.GetString("ClassesView_CannotOpenBeforSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قم بتحديد مسار حفظ صور العقود في قائمة الخيارات أولاً.
        /// </summary>
        internal static string ContractView_ContPhoFolderMissingMsg {
            get {
                return ResourceManager.GetString("ContractView_ContPhoFolderMissingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم العقد غير موجود.
        /// </summary>
        internal static string ContractView_ContractNotExist {
            get {
                return ResourceManager.GetString("ContractView_ContractNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تحدد مبلغ التأمين 
        ///هل تريد الإستمرار؟.
        /// </summary>
        internal static string ContractView_DepositMissing {
            get {
                return ResourceManager.GetString("ContractView_DepositMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل يوم تسجيل العقد.
        /// </summary>
        internal static string ContractView_InvalidForPrint1 {
            get {
                return ResourceManager.GetString("ContractView_InvalidForPrint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكد من مبلغ التأمين.
        /// </summary>
        internal static string ContractView_InvalidForPrint2 {
            get {
                return ResourceManager.GetString("ContractView_InvalidForPrint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل الحي الواقع فيه العقار.
        /// </summary>
        internal static string ContractView_InvalidForPrint3 {
            get {
                return ResourceManager.GetString("ContractView_InvalidForPrint3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل التاريخ الهجري لتسجيل العقد.
        /// </summary>
        internal static string ContractView_InvalidForPrint4 {
            get {
                return ResourceManager.GetString("ContractView_InvalidForPrint4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل التاريخ الميلادي لتسجيل العقد.
        /// </summary>
        internal static string ContractView_InvalidForPrint5 {
            get {
                return ResourceManager.GetString("ContractView_InvalidForPrint5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل المدينة الواقع فيها العقار.
        /// </summary>
        internal static string ContractView_InvalidForPrint6 {
            get {
                return ResourceManager.GetString("ContractView_InvalidForPrint6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إحفظ البيانات أولاً.
        /// </summary>
        internal static string ContractView_NotSaved {
            get {
                return ResourceManager.GetString("ContractView_NotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد مستأجر بهذا الرقم.
        /// </summary>
        internal static string CustomerView_CustomerNotExist {
            get {
                return ResourceManager.GetString("CustomerView_CustomerNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الفاكس يجب ان يكون 9 ارقام مع مفتاح المنطقة.
        /// </summary>
        internal static string CustomerView_InvalidFax {
            get {
                return ResourceManager.GetString("CustomerView_InvalidFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية يجب أن يكون 10 أرقام.
        /// </summary>
        internal static string CustomerView_InvalidId {
            get {
                return ResourceManager.GetString("CustomerView_InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال يجب ان يكون 10 أرقام.
        /// </summary>
        internal static string CustomerView_InvalidMobile {
            get {
                return ResourceManager.GetString("CustomerView_InvalidMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال الجنسية.
        /// </summary>
        internal static string CustomerView_InvalidNationality {
            get {
                return ResourceManager.GetString("CustomerView_InvalidNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف يجب ان يكون 9 ارقام مع مفتاح المنطقة.
        /// </summary>
        internal static string CustomerView_InvalidPhone {
            get {
                return ResourceManager.GetString("CustomerView_InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد حذف السجل؟.
        /// </summary>
        internal static string DeletePrompetMsg {
            get {
                return ResourceManager.GetString("DeletePrompetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال نص الرسالة الموجهة في المطالبة في الخيارات أولاً.
        /// </summary>
        internal static string ExceMsg_ClaimLetterMissing {
            get {
                return ResourceManager.GetString("ExceMsg_ClaimLetterMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل تاريخ نهاية العقد.
        /// </summary>
        internal static string MonthlyContractView_EndDateMissing {
            get {
                return ResourceManager.GetString("MonthlyContractView_EndDateMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا توجد نتائج للبحث.
        /// </summary>
        internal static string ObjectNotFoundExcMsg {
            get {
                return ResourceManager.GetString("ObjectNotFoundExcMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد الخروج دون حفظ؟.
        /// </summary>
        internal static string SavePrompetMsg {
            get {
                return ResourceManager.GetString("SavePrompetMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد العقد.
        /// </summary>
        internal static string ScheduleView_ContractMissing {
            get {
                return ResourceManager.GetString("ScheduleView_ContractMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه المستأجر سبق ان تعهد.
        /// </summary>
        internal static string ScheduleView_CustomerAlreadyScheduled {
            get {
                return ResourceManager.GetString("ScheduleView_CustomerAlreadyScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ دفعات التعهد يجب ان يكون خلال السنة الحالية.
        /// </summary>
        internal static string ScheduleView_DetailDateMissing {
            get {
                return ResourceManager.GetString("ScheduleView_DetailDateMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال دفعة تعهد واحدة على الأقل.
        /// </summary>
        internal static string ScheduleView_DetailsMissing {
            get {
                return ResourceManager.GetString("ScheduleView_DetailsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع دفعات التعهد يجب أن يكون مساوياً لإحمالي قيمة العقد.
        /// </summary>
        internal static string ScheduleView_InvalidAmoutDueTotal {
            get {
                return ResourceManager.GetString("ScheduleView_InvalidAmoutDueTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد تعهد بهذا الرقم.
        /// </summary>
        internal static string ScheduleView_ScheduleNotExist {
            get {
                return ResourceManager.GetString("ScheduleView_ScheduleNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد المتعهد.
        /// </summary>
        internal static string ScheduleView_SignerMissing {
            get {
                return ResourceManager.GetString("ScheduleView_SignerMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المتعهد تم تسجيله من قبل.
        /// </summary>
        internal static string SignerView_SignerExist {
            get {
                return ResourceManager.GetString("SignerView_SignerExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال تاريخ الهوية.
        /// </summary>
        internal static string SignerView_SignerIdDateMissing {
            get {
                return ResourceManager.GetString("SignerView_SignerIdDateMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال رقم الهوية.
        /// </summary>
        internal static string SignerView_SignerIdMissing {
            get {
                return ResourceManager.GetString("SignerView_SignerIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال رقم الجوال من 10 أرقام.
        /// </summary>
        internal static string SignerView_SignerMobileMissing {
            get {
                return ResourceManager.GetString("SignerView_SignerMobileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال اسم المتعهد.
        /// </summary>
        internal static string SignerView_SignerNameMissing {
            get {
                return ResourceManager.GetString("SignerView_SignerNameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايوجد متعهد بهذا الرقم.
        /// </summary>
        internal static string SignerView_SignerNotExist {
            get {
                return ResourceManager.GetString("SignerView_SignerNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل السنة بشكل صحيح
        ///السنة يجب أن تكون أكبر من 1433.
        /// </summary>
        internal static string SyncView_InvalidYear {
            get {
                return ResourceManager.GetString("SyncView_InvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnsignedContract {
            get {
                object obj = ResourceManager.GetObject("UnsignedContract", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
