//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jsa.ViewsModel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BaMusaSoft\\JeddahStation\\Property.mdb")]
        public string IrsDbPath {
            get {
                return ((string)(this["IrsDbPath"]));
            }
            set {
                this["IrsDbPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1434")]
        public string CurrentYear {
            get {
                return ((string)(this["CurrentYear"]));
            }
            set {
                this["CurrentYear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Branch {
            get {
                return ((int)(this["Branch"]));
            }
            set {
                this["Branch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" />")]
        public global::System.Collections.Specialized.StringCollection PeriodSchedulesGridPreference {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PeriodSchedulesGridPreference"]));
            }
            set {
                this["PeriodSchedulesGridPreference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BaMusaSoft\\JeddahStation\\Templates\\PeriodSchedules.xltx")]
        public string PeriodSchedulesExcelTemplate {
            get {
                return ((string)(this["PeriodSchedulesExcelTemplate"]));
            }
            set {
                this["PeriodSchedulesExcelTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BaMusaSoft\\JeddahStation\\Templates\\ContractsReport.xltx")]
        public string ContractReportExcelTemplate {
            get {
                return ((string)(this["ContractReportExcelTemplate"]));
            }
            set {
                this["ContractReportExcelTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LogFilePath {
            get {
                return ((string)(this["LogFilePath"]));
            }
            set {
                this["LogFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BaMusaSoft\\JeddahStation\\Templates\\RGL.xlt")]
        public string RglTemplatePath {
            get {
                return ((string)(this["RglTemplatePath"]));
            }
            set {
                this["RglTemplatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradedVersion {
            get {
                return ((bool)(this["UpgradedVersion"]));
            }
            set {
                this["UpgradedVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("نآمل سرعة مراجعة إدارة الوقف لتسديد المستحق عليكم والمبين أدناه وقدره ")]
        public string ClaimTextPartOne {
            get {
                return ((string)(this["ClaimTextPartOne"]));
            }
            set {
                this["ClaimTextPartOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(". وذلك خلال أسبوع من تاريخه")]
        public string ClaimTextPartTwo {
            get {
                return ((string)(this["ClaimTextPartTwo"]));
            }
            set {
                this["ClaimTextPartTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClaimTemplatePath {
            get {
                return ((string)(this["ClaimTemplatePath"]));
            }
            set {
                this["ClaimTemplatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Abdullah\\Pictures\\2013-02-21")]
        public string ScanShareFolder {
            get {
                return ((string)(this["ScanShareFolder"]));
            }
            set {
                this["ScanShareFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ContractsPhotosPath {
            get {
                return ((string)(this["ContractsPhotosPath"]));
            }
            set {
                this["ContractsPhotosPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BaMusaSoft\\JeddahStationProject\\Templates")]
        public string CustomerCardTemplatePath {
            get {
                return ((string)(this["CustomerCardTemplatePath"]));
            }
            set {
                this["CustomerCardTemplatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BaMusaSoft\\JeddahStation\\Templates\\MonthlyContract.dotx")]
        public string MonthlyContractTemplate {
            get {
                return ((string)(this["MonthlyContractTemplate"]));
            }
            set {
                this["MonthlyContractTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScheduleTemplatePath {
            get {
                return ((string)(this["ScheduleTemplatePath"]));
            }
            set {
                this["ScheduleTemplatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RentTempatePath {
            get {
                return ((string)(this["RentTempatePath"]));
            }
            set {
                this["RentTempatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MaintTemplatePath {
            get {
                return ((string)(this["MaintTemplatePath"]));
            }
            set {
                this["MaintTemplatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int AppointDueDays {
            get {
                return ((int)(this["AppointDueDays"]));
            }
            set {
                this["AppointDueDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\BaMusaSoft\\JeddahStationProject\\Templates\\GeneralContract.docx")]
        public string GeneralContractTemplate {
            get {
                return ((string)(this["GeneralContractTemplate"]));
            }
            set {
                this["GeneralContractTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ClassesTemplate {
            get {
                return ((string)(this["ClassesTemplate"]));
            }
            set {
                this["ClassesTemplate"] = value;
            }
        }
    }
}
